/*
gubobjs.gubobjsUiVersion="A"=All (Banner8 & Banner9)
gubobjs.gubobjsUiVersion="B"=Banner8 Only
gubobjs.gubobjsUiVersion="C"=Banner9 Only
gubobjs.gubobjsUiVersion="D"=Unified Menu All (Ban8&Ban9)
gubobjs.gubobjsUiVersion="E"=Unified Menu Ban9 Only
*/


connect general/&&general_password

PROMPT insert domain object into GUBOBJS
INSERT INTO GUBOBJS
(GUBOBJS_NAME,
GUBOBJS_DESC, 
GUBOBJS_OBJT_CODE,
GUBOBJS_SYSI_CODE, 
GUBOBJS_USER_ID,
GUBOBJS_ACTIVITY_DATE,
GUBOBJS_HELP_IND, 
GUBOBJS_EXTRACT_ENABLED_IND, 
GUBOBJS_UI_VERSION)
SELECT 
'ELIVE_EXAMPLE4_UPLOAD_CHARGES',
'Elive Example 4 Upload Charges',
'FORM',
'G',
USER,
SYSDATE,
'N',
'N',
'D'
FROM DUAL
WHERE NOT EXISTS
(SELECT NULL FROM GUBOBJS WHERE GUBOBJS_NAME = 'ELIVE_EXAMPLE4_UPLOAD_CHARGES');


INSERT INTO GUBOBJS
(GUBOBJS_NAME,
GUBOBJS_DESC, 
GUBOBJS_OBJT_CODE,
GUBOBJS_SYSI_CODE, 
GUBOBJS_USER_ID,
GUBOBJS_ACTIVITY_DATE,
GUBOBJS_HELP_IND, 
GUBOBJS_EXTRACT_ENABLED_IND, 
GUBOBJS_UI_VERSION)
SELECT 
'ELIVE_EXAMPLE4_UPD_STU_ACCTS',
'Elive Example 4 Upd stu accts',
'FORM',
'G',
USER,
SYSDATE,
'N',
'N',
'D'
FROM DUAL
WHERE NOT EXISTS
(SELECT NULL FROM GUBOBJS WHERE GUBOBJS_NAME = 'ELIVE_EXAMPLE4_UPD_STU_ACCTS');


INSERT INTO GUBOBJS
(GUBOBJS_NAME,
GUBOBJS_DESC, 
GUBOBJS_OBJT_CODE,
GUBOBJS_SYSI_CODE, 
GUBOBJS_USER_ID,
GUBOBJS_ACTIVITY_DATE,
GUBOBJS_HELP_IND, 
GUBOBJS_EXTRACT_ENABLED_IND, 
GUBOBJS_UI_VERSION)
SELECT 
'ELIVE_EXAMPLE4_UPD_STU_PRGRS',
'Elive Example 4 Upd stu progrss',
'FORM',
'G',
USER,
SYSDATE,
'N',
'N',
'D'
FROM DUAL
WHERE NOT EXISTS
(SELECT NULL FROM GUBOBJS WHERE GUBOBJS_NAME = 'ELIVE_EXAMPLE4_UPD_STU_PRGRS');


PROMPT add grants to pl/sql API  used by domain

GRANT SELECT,INSERT,UPDATE,DELETE  on TAISMGR.TZRPRKG TO BAN_DEFAULT_PAGEBUILDER_M; 

GRANT EXECUTE  on BANINST1.GZK_EXAMPLE_4 TO BAN_DEFAULT_PAGEBUILDER_M; 
PROMPT

COMMIT;
